# Generated by Django 4.1.6 on 2023-02-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_rename_newsphoto_newscontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='photo_preview',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='practice.gallery'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='newscontent',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='practice.news'),
        ),
    ]
